# Site settings
title: Nathan Contino
email: ncontino@u.rochester.edu
description: > # this means to ignore newlines until "baseurl:"
  Nathan Contino's personal website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# User setting
owner: Start Bootstrap
email: name@example.com
facebook_username: example
twitter_username: example
github_username: example
address:
  - line: 500 Joseph C Wilson Blvd
  - line: "Rochester, NY 14627"
  # Feel free to add more lines here 
telephone: (123) 456-7890
copyright: 2016

# API settings
google_api_key: AIzaSyA8H0jVz_6Hc273rqNYKQ6AAiBvQfVKmYQ

# Build settings
markdown: kramdown