# Dependencies
markdown:            kramdown
highlighter:         rouge

# Gems (for Jekyll 3.0)
gems: [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Nathan Contino's Personal Website
tagline:             'learn about me!'
description:         'Created by Nathan Contino'
url:                 nathan-contino.github.io
baseurl:             /
paginate:            7

# About/contact
author:
  name:              Nathan Contino
  url:               nathan-contino.github.io
  email:             ncontino(at)u.rochester.edu

# Custom vars
version:             2.0

# Social Media
github:				http://github.com/nathan-contino

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Rizky Ariestiyansyah
  codename:			Naringu
  link:             https://github.com/ariestiyansyah/naringu
